version: '3'

networks:
  ms_budisuryadi_betest:

services:
  mongo-database:
    image: "mongo:latest"
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    networks:
      - ms_budisuryadi_betest
  redis-database:
    image: "redis"
    ports:
      - 6379:6379
    networks:
    - ms_budisuryadi_betest
  web:
    build: .
    ports:
      - 1234:1234
    environment:
      - MONGO_URL=mongodb://mongo-database:27017/db_budisuryadi_betest
      - REDIS_URL=redis://redis-database:6379
    depends_on:
      - mongo-database
      - redis-database
    networks:
      - ms_budisuryadi_betest